project: 
  type: website
  
website: 
  page-navigation: true
  title: "Notatki do przedmiotu PMK" 
  site-url: "https://mdaniol.github.io/pmk-notes/" 
  repo-url: https://github.com/MDaniol/pmk-notes 
  repo-actions: [edit, issue]

  page-footer:
    right: "This page is built with ❤️ and [Quarto](https://quarto.org/)."
    left: "&copy; CC-By Mateusz Danioł, 2022"
    
  sidebar:
    logo: "images/PMK_hex.png"
    pinned: true
    align: center
    # tools: 
      # - icon: globe
      #   href: https://openscapes.org
      #   text: "Openscapes.org"
      # - icon: github
      #   href: https://github.com/openscapes/quarto-website-tutorial
      #   text: "Quarto website tutorial"
      # - icon: twitter
      #   href: https://twitter.com/openscapes
      #   text: "Openscapes Twitter"         

    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - href: index.qmd
        text: Na początek
       
      - href: labs/lab1.qmd
        text: Laboratorium 1

      - href: labs/lab2.qmd
        text: Laboratorium 2

      - href: labs/lab3.qmd
        text: Laboratorium 3

      # - section: quarto-workflows/index.qmd
      #   text: Materiały Pomocnicze
      #   contents: 
      #     - quarto-workflows/browser.md
      #     - quarto-workflows/rstudio.qmd
      #     - quarto-workflows/jupyter.md 
      # - href: learning-more.qmd
      #   text: Dodatkowe Źródła
      # - href: transition-from-rmarkdown.qmd
      #   text: Przykładowe projekty


format:
  html:
    theme:
      light: [cosmo, theme.scss] # from https://github.com/sta210-s22/website/blob/main/_quarto.yml
      dark: [cosmo, theme-dark.scss]
    code-copy: true
    code-overflow: wrap
    toc: true


filters:
  - include-files.lua
  - quarto

  
